### ISSUE TITLE
POST /companies/addCompany on Heroku fails

### ISSUE THREAD

**Issue by davidgrieser** [404-bug-not-found/100_percent_capstone#40]
Attempted to POST:

```.json
{
    "invoice_number": "FDM-123",
    "name": "Freddie Mac",
    "contact_name": "Zxander",
    "contact_title": "Accounts Payable",
    "contact_phone_number": "1-123-456-7890",
    "addresses": [
        {
            "id": 3,
            "addr_line1": "123 Dr",
            "city": "Houston",
            "state": "TX",
            "zip": "1000"
        }
    ]
}
```

Received the following response:

```.json
{
    "timestamp": "2021-05-18T20:52:02.230+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "message": "",
    "path": "/companies/addCompany"
}
```

I remember that this was an issue brought up on Friday (May 14th) and when asked if it was fixed May 15th the response was yes, but there seems to be some sort of problem. It could be unrelated, but Heroku should be functioning.

**Comment by 404-bug-not-found** [comment]
After latest PR was merged and deployed, some of the entities structure was changed, hence it was giving 500 error. After recreating DB and restarting dynos, everything is working fine. Also, I noticed, while posting company, you were trying to include address as well, which wont work. You have to ad company first, followed by add address, and while adding address, provide the company name. Sample POSTs are as follows - 

**Add Company:**
-----------------
{"invoice_number":"CTS-123","name":"Cognizant","contact_name":"David","contact_title":"Accounts Payable","contact_phone_number":"1-123-456-7890"}

**AddAddress:**
---------------
{"addr_line1":"123 Dr","city":"Houston","state":"TX","zip":"1000",**"companyName":"Cognizant"**}

**Comment by 404-bug-not-found** [comment]
Closing this bug
